export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_UPDATE: 'USER_STATUS_UPDATE',

  BRANCH_ASSIGN: 'BRANCH_ASSIGN',
  PROFILE_UPDATE: 'PROFILE_UPDATE',

  QUOTATION_READ: 'QUOTATION_READ',
  QUOTATION_CREATE: 'QUOTATION_CREATE',
  QUOTATION_UPDATE: 'QUOTATION_UPDATE',
  QUOTATION_DELETE: 'QUOTATION_DELETE',

  SYSTEM_LOG_READ: 'SYSTEM_LOG_READ',
  SYSTEM_LOG_EXPORT: 'SYSTEM_LOG_EXPORT',

  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
};
