export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_UPDATE: 'USER_STATUS_UPDATE',

  BRANCH_ASSIGN: 'BRANCH_ASSIGN',
  PROFILE_UPDATE: 'PROFILE_UPDATE',

  SALES_READ: 'SALES_READ',
  SALES_CREATE: 'SALES_CREATE',
  SALES_UPDATE: 'SALES_UPDATE',
  SALES_DELETE: 'SALES_DELETE',
};